### PR TITLE
Use wailsLogger in auto updater

### LINKED ISSUE #56: Make auto updater use the logger file
Use the created logger in `main.go` along with the logging to console (this is needed for the pipeline)

### PR DESCRIPTION
**Pull request by jordan-dalby**
Changes the auto updater to use wailsLogger rather than printf.

Closes #56

### CODE REVIEW

**Comment by JensvandeWiel** [comment]
Hey, @jordan-dalby do you have discord, if so i can give you contributor role

**Review by JensvandeWiel — APPROVED** [review]
Looks great

**Comment by jordan-dalby** [comment]
> Hey, @jordan-dalby do you have discord, if so i can give you contributor role

Hi, yeah I do it's 'jordna'.

**Comment by JensvandeWiel** [comment]
> > Hey, @jordan-dalby do you have discord, if so i can give you contributor role
> 
> Hi, yeah I do it's 'jordna'.

i've added you

**Pull request merged**
