### PR TITLE
#121: Fix auto-save

### PR DESCRIPTION
**Pull request by jordan-dalby**
This PR fixes auto-save divide by 0 error.

### CODE REVIEW

**Review by JensvandeWiel — CHANGES_REQUESTED** [review]
add the check in CheckIfServerCorrect() and don't check in the frontend

**Comment by JensvandeWiel** [comment]
@jordan-dalby also, make sure when a new server is made that the default value is not 0, you can do this in: helpers.go -> generateNewDefaultServer

**Comment by jordan-dalby** [comment]
> add the check in CheckIfServerCorrect() and don't check in the frontend

Adding this check will break existing server json files. Even with the generateNewDefaultServer changes. Ideally, we'd want to assign a value it's default if it's missing, prevents breakages like that happening in the future.

**Comment by JensvandeWiel** [comment]
that is true, maybe you can add a check there if it is 0 put it back to the default val you set in generateNewDefaultServer i think 15 minutes is good for this

**Comment by jordan-dalby** [comment]
Sorted.

**Review by JensvandeWiel — APPROVED** [review]
great

**Pull request merged**
